### ISSUE TITLE
TivaWare?

### ISSUE THREAD

**Issue by theotherjimmy** [ut-ras/Rasware#47]
I kinda had to do this conversion for mercury, should we merge it into master after testing?

**Comment by robz** [comment]
yes!

**Comment by geky** [comment]
Out of curiosity, what happens when we flash StellarisWare boards with TivaWare code? If we're lucky enough, it might work. Has anyone tried it?

**Comment by geky** [comment]
Also, Rasware generally worked on the LM4Fs without taking care of #39, but from 445M the muxing functions definitely seem to be necessary on the TM4Cs. Just a heads up if anyone finds that an alternate function is suddenly not working.
